### ISSUE TITLE
bug: Error executing vim.schedule lua callback: .../.local/share/nvim/lazy/lazydev.nvim/lua/lazydev/buf.lua:151: bad argument #1 to 'ipairs' (table expected, got nil)

### ISSUE THREAD

**Issue by yavorski** [folke/lazydev.nvim#10]
### Did you check docs and existing issues?

- [X] I have read all the lazydev.nvim docs
- [X] I have searched the existing issues of lazydev.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

Arch Linux 6.9.3-arch1-1

### Describe the bug

The plugin throws error when starting with `nvim ~/.config/nvim/init.lua`, but it works correctly when I am editing the `init.lua` in my repository directory. I think it throws when there isn't a lua directory e.g. `~/.config/nvim/lua/`, e.g. when you have only single `init.lua` file there. Here is the error.

```lua
Error executing vim.schedule lua callback: .../.local/share/nvim/lazy/lazydev.nvim/lua/lazydev/buf.lua:151: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
	[C]: in function 'ipairs'
	.../.local/share/nvim/lazy/lazydev.nvim/lua/lazydev/buf.lua:151: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps To Reproduce

1. delete lua dir if any `rm -r ~/.config/nvim/lua/`
2. start nvim with `nvim ~/.config/nvim/init.lua`

### Expected Behavior

To not throw error and to work correctly.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/lazydev.nvim",
  -- add any other plugins here
  {
    "folke/lazydev.nvim",
    dependencies = {{ "bilal2453/luvit-meta" }},
    ft = "lua",
    opts = {
      library = { "luvit-meta/library" }
    }
  }
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
-- nothing else
```

**Comment by folke** [comment]
Should be fixed, but would be great if you can confirm!

**Comment by yavorski** [comment]
It does not throw, but it is not working either... Also it is printing directories now. It works when I create the `~/.config/nvim/lua/` dir manually. See screenshots.

![screenshot-02-06-2024-23-56-25](https://github.com/folke/lazydev.nvim/assets/3436517/41c7378c-733b-44f1-bf1d-4a26d1520491)

![screenshot-02-06-2024-23-55-11](https://github.com/folke/lazydev.nvim/assets/3436517/9a126429-5343-4b22-bd7a-7fde7ac02baf)

**Comment by folke** [comment]
Just removed that debug.
Now I understand what you mean with init.lua. Will check

**Comment by folke** [comment]
What does `:=vim.lsp.buf.list_workspace_folders()` show?

**Comment by folke** [comment]
I think this is the problem: https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/lua_ls.lua#L22

Your LuaLS is in single file mode, no workspace.

When you create the lua folder, you're in a workspace.

**Comment by folke** [comment]
Although, even in that case it still works for me....

**Comment by yavorski** [comment]
> What does `:=vim.lsp.buf.list_workspace_folders()` show?

Empty table `{}`
I have added workaround to my config now to create the dir if it does not exists, so it's not a big deal.

```lua
Lazy.use {
  "folke/lazydev.nvim",
  -- dir = "~/dev/open-sos/lazydev.nvim",
  dependencies = {{ "bilal2453/luvit-meta" }},
  ft = "lua",
  opts = {
    library = { "luvit-meta/library" }
  },
  init = function()
    local luadir = vim.fn.expand("~/.config/nvim/lua/")
    if not vim.loop.fs_stat(luadir) then
      vim.fn.mkdir(luadir)
    end
  end
}
```

**Comment by folke** [comment]
And this? `:=vim.lsp.get_clients({name = "lua_ls"})[1].root_dir`

**Comment by yavorski** [comment]
nil, 

![screenshot-03-06-2024-01-08-18](https://github.com/folke/lazydev.nvim/assets/3436517/3ff7cc73-3272-4fd7-a149-417d86031ff3)

**Comment by folke** [comment]
Should work now with single file support

**Comment by yavorski** [comment]
It is working now. Thank you!
