### ISSUE TITLE
bug: lazydev.nvim notifies the same thing on every nvim launch

### ISSUE THREAD

**Issue by muneebusmani** [folke/lazydev.nvim#11]
### Did you check docs and existing issues?

- [X] I have read all the lazydev.nvim docs
- [X] I have searched the existing issues of lazydev.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0 

### Operating system/version

Archlinux

### Describe the bug

i get this notification whenever i launch neovim it is going on since last 1 or 2 updates in lazydev.nvim
## ~/.config/lazyvim
- `/usr/share/nvim/runtime/lua`
- **LazyVim** `~/.local/share/lazyvim/lazy/LazyVim/lua`
- `~/.local/share/lazyvim/lazy/luvit-meta/library`

### Steps To Reproduce

1. Open neovim if you have this plugin enabled
2. Lazy Sync
3. restart nvim
4. try it with multiple lazyvim configurations and all will have this issue

i Lazy sync'ed  in my main config and i had this notification popup everytime, then i tried to reproduced in my Lazyvim starter templete and it happened there too

### Expected Behavior

it shouldn't pop up this notification

**Comment by folke** [comment]
Yeah, I accidentally pushed an update where debug was enabled. Sorry!

**Comment by folke** [comment]
So just update and it will be gone.
