### ISSUE TITLE
bug: Appears to not do anything

### ISSUE THREAD

**Issue by sid-6581** [folke/lazydev.nvim#12]
### Did you check docs and existing issues?

- [X] I have read all the lazydev.nvim docs
- [X] I have searched the existing issues of lazydev.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

Windows 11

### Describe the bug

I know the title is vague, but I tried moving from `neodev` to `lazydev` and couldn't get it to do anything. The `lua_ls` settings weren't updated with the runtime and plugin paths (at least as far as I could tell), and I didn't have type info for `vim` nor my plugins.

To convince myself I wasn't going insane, I did a fresh clone of `LazyVim` and confirmed that I was having the same issues there. This is a screenshot from `example.lua` in `LazyVim`. The latest version, with `lazy.nvim` and all plugins updated.

![image](https://github.com/folke/lazydev.nvim/assets/28602336/f2326973-5584-47f1-b5e0-6918502d07d6)

This is on Windows with nvim 0.10.0. The nvim version should be fine, so maybe it's a Windows issue? It wouldn't be the first time something like a wrong path slash brings everything to a halt, but I'm not sure if that's what's going on here. `neodev` works fine on Windows.

### Steps To Reproduce

1. Clone Lazyvim
2. Start nvim
3. Wait for plugins to install, and open `example.lua` from the config.

### Expected Behavior

Expect `vim` and plugins to have types.

**Comment by sid-6581** [comment]
> @sid-6581 try:
> 
> ```lua
>   require("lazydev").setup({
>     debug = false,
>     library = {
>       "nvim-cmp/lua/cmp/types",
>     },
>   })
> ```

I'm just using the `LazyVim` stock setup, which I would imagine should work out of the box. That change also wouldn't help with `vim` not being defined, nor would it help with every other plugin's types.

**Comment by folke** [comment]
Probably a path issue indeed. Will look into it!

**Comment by sid-6581** [comment]
Thanks! I started to look into it myself, but lazydev was changing so rapidly that I decided to tackle the path (and other issues) in the nvim-cmp cmdline source while this settled down, lol.

Appreciate all the awesome plugins!

**Comment by folke** [comment]
Should all work now on Windows. Would be great if you can confirm!

**Comment by perrin4869** [comment]
[the latest commit](https://github.com/folke/lazydev.nvim/commit/f98d85a16771282caceeefa0d9a65336f8b44437) is importing `lazy.core.util`, but I don't use lazy as my package manager 😅

**Comment by fent** [comment]
I'm also having this issue, but on linux. and strangely, switching back to neodev, i still get `undefined global vim` when i previously didn't. did lazydev change something?

**Comment by folke** [comment]
@perrin4869 fixed now.

@fent are you sure you're using the latest version? If so, can you enabled `opts.debug = true` and paste what it says?

**Comment by perrin4869** [comment]
thanks!

**Comment by karamanliev** [comment]
I am also experiencing problems on linux, getting `vim`, `require`, and etc as `Undefined global`, even though I am getting types:
![image](https://github.com/folke/lazydev.nvim/assets/22788016/5e94c164-0084-4c5b-a1f9-ba9dfdd919b2)
![image](https://github.com/folke/lazydev.nvim/assets/22788016/c54444f2-5f65-4000-8eed-d054f52e0dcb)

Here are the debug logs:
```lua
   Info  11:39:24 AM notify.info lazydev.nvim ## ~/dotfiles/.config/nvim
- **runtime** `/usr/share/nvim/runtime/lua`
- **telescope.nvim** `~/.local/share/nvim/lazy/telescope.nvim/lua`
- **nvim-ufo** `~/.local/share/nvim/lazy/nvim-ufo/lua`
- **gitsigns.nvim** `~/.local/share/nvim/lazy/gitsigns.nvim/lua`
- **cmp-nvim-lsp** `~/.local/share/nvim/lazy/cmp-nvim-lsp/lua`
- **ts-error-translator.nvim** `~/.local/share/nvim/lazy/ts-error-translator.nvim/lua`
- **nvim-lspconfig** `~/.local/share/nvim/lazy/nvim-lspconfig/lua`
- **mason.nvim** `~/.local/share/nvim/lazy/mason.nvim/lua`
- **mason-tool-installer.nvim** `~/.local/share/nvim/lazy/mason-tool-installer.nvim/lua`
- **mason-lspconfig.nvim** `~/.local/share/nvim/lazy/mason-lspconfig.nvim/lua`
- **tsc.nvim** `~/.local/share/nvim/lazy/tsc.nvim/lua`
- **goto-preview** `~/.local/share/nvim/lazy/goto-preview/lua`
   Info  11:39:24 AM notify.info lazydev.nvim ## [single]
- **runtime** `/usr/share/nvim/runtime/lua`
```

**Comment by folke** [comment]
That looks correct. Probably disagnostics that are outdated. Does it fix itself when making an edit to the file?

**Comment by folke** [comment]
Also, make sure you are using a recent LuaLS version

**Comment by karamanliev** [comment]
> That looks correct. Probably disagnostics that are outdated. Does it fix itself when making an edit to the file?

Yeah, actually it does, thank you for clarifying.

**Comment by folke** [comment]
I've sometimes noticed that as well. Either a bug in Neovim, or in LuaLS.
I've tried working around it, but couldn't find anything I could do
