### ISSUE TITLE
feature: Exclude plugin files when contribute a plugin

### ISSUE THREAD

**Issue by nanozuki** [folke/lazydev.nvim#17]
### Did you check the docs?

- [X] I have read all the lazydev.nvim docs

### Is your feature request related to a problem? Please describe.

When I contribute a plugin I installed for my neovim, there will be some "Duplicated Definitions" diag warnings.

<img width="864" alt="图片" src="https://github.com/folke/lazydev.nvim/assets/4208028/4ba6dbf1-48f0-4c72-9113-2383a26e17e5">

<img width="928" alt="图片" src="https://github.com/folke/lazydev.nvim/assets/4208028/dc96d5e9-51c3-468e-a780-cac0a99fe014">

And issue #13 did not fix me.

### Describe the solution you'd like

Adding a callback function to opts, allows me to exclude a plugin's files.

### Describe alternatives you've considered

As neodev.nvim, don't add plugin files in projects are not neovim config repository.

**Comment by folke** [comment]
That's to be expected. Won't fix this.
If you use your development version of the plugin in Neovim, then you won't see duplicates

**Comment by folke** [comment]
dev =true indeed
