### ISSUE TITLE
diagnostics for `missing required fields`

### ISSUE THREAD

**Issue by gennaro-tedesco** [folke/lazydev.nvim#18]
More than an issue this is a request for explanation, I probably misunderstand how `lazydev` interacts with diagnostics if at all.

I have switched from `neodev` to `lazydev` upon the same version of lua language server and I have noticed that, in correspondence of some plugins, diagnostics of "missing required fields" are shown although settings for said plugins default to a pre-defined value should those options not be explicitly set (which means those settings aren't really required after all).

Example below if from `nvim-treesitter`, which you can probably reproduce (same happens for other plugins):

![Screenshot 2024-06-04 at 09 36 56](https://github.com/folke/lazydev.nvim/assets/15387611/38311c8c-fdb2-46e4-9ffe-917e3e9c1cb3)

I would guess this might have to do with some options indicated as `type required`(if such thing exists at all)? I would expect this to have nothing to do with `lazydev` (since diagnostics are operated by the language server), however I only see them after replacing `neodev` with it.

Does `lazydev` have a say on such diagnostics at all?

**Comment by folke** [comment]
This has nothing to do with lazydev. That's a new diagnstic in LuaLS that got introduced at some point
