### ISSUE TITLE
bug: not working other than in `init.lua`

### ISSUE THREAD

**Issue by Congee** [folke/lazydev.nvim#26]
### Did you check docs and existing issues?

- [X] I have read all the lazydev.nvim docs
- [X] I have searched the existing issues of lazydev.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev+d490a7b

### Operating system/version

macOS 14.2.1

### Describe the bug

I have a directory structure of
```
~/config/nvim/lua
----------------- init.lua
----------------- plugins.lua
```

Everything works well in `init.lua` including lsp hovering and completion, nothing works in other files like `plugins.lua`. A common error is "Undefined global `vim`" in `plugins.lua`. `lazy.nvim` is my package manager and `neodev.nvim` has been completely nuked (it provided type definitions with lazydev.nvim, ironically)

I have also played around with the source code of lazydev.nvim and still have no idea why it decides not to help in other files.

Here is the debug output:
```
:LazyDev debug
## ~/.nix/config/nvim/lua
- **runtime** `/nix/store/2kbf77bi1r9fnqx6nal1qy0c02m8wd5h-neovim-unwrapped-nightly/share/nvim/runtime/lua`
- **nvim** `~/.nix/config/nvim/lua`
```
```lua
settings = {
  Lua = {
    runtime = {
      path = { "?.lua", "?/init.lua" },
      pathStrict = true,
      version = "LuaJIT"
    },
    workspace = {
      checkThirdParty = false,
      ignoreDir = { "/lua" },
      library = { "/nix/store/2kbf77bi1r9fnqx6nal1qy0c02m8wd5h-neovim-unwrapped-nightly/share/nvim/runtime/lua", "/Users
/cwu/.nix/config/nvim/lua" }
    }
  },
  <metatable> = {
    __tostring = <function 1>
  }
}
```

### Steps To Reproduce

ughhh

### Expected Behavior

features of lazydev.nvim are available in other files as well.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/lazydev.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
What happens when you edit the files from:
-  ~/.nix/config/nvim/lua
-  ~/.config/nvim/lua

**Comment by Congee** [comment]
> What happens when you edit the files from:
> 
>     * ~/.nix/config/nvim/lua
> 
>     * ~/.config/nvim/lua

Woah that's a prompt reply. The behavior is the same as in the issue reported.

One thing interesting is flaky type annotation path for`~/.wezterm.lua`.

If I wait patiently for lua_ls to completely load, goto definition on `require('wezterm')` leads to `~/.local/share/nvim/lazy/wezterm-types/types/config/init.lua`. If I execute it fast before lua_ls completely loads, it leads to `~/.local/share/nvim/lazy/wezterm-types/wezterm.lua`. Maybe it's related to the path issue here, especially about how `init.lua` is treated, maybe it's different thing worth investigating.

(Thanks for your plugins 😉)

**Comment by folke** [comment]
All your config and debug output look correct.
Sometimes LuaLS diagnostics are not correct in the active buffer after the config was changed.
This is a bug somewhere either in Neovim or in LuaLS. I actually did a PR in LuaLS last week to fix this partially.

If you see `vim` undefined, wait till everything is loaded and then add a new empty line.
Does that fix the diagnostics?

**Comment by Congee** [comment]
Well, this one is different from https://github.com/folke/lazydev.nvim/issues/12#issuecomment-2144852606. `vim` is consistently undefined in files other than `init.lua`

**Comment by folke** [comment]
From your config, "/nix/store/2kbf77bi1r9fnqx6nal1qy0c02m8wd5h-neovim-unwrapped-nightly/share/nvim/runtime/lua" is part of your workspace library, so that is all correct.
No idea when you still get undefined globals, since the library has been added.
Closing

**Comment by folke** [comment]
Are you 100% certain those errors are coming from `lua_ls` and not something like `luacheck`?

**Comment by Congee** [comment]
> Are you 100% certain those errors are coming from `lua_ls` and not something like `luacheck`?

yes. I only have `lus_ls` installed related to lua

**Comment by Congee** [comment]
A`.luarc.json` fie is next to `init.lua`. Deleting it worked.

**Comment by dhruvinsh** [comment]
> A .luarc.json fie is next to init.lua. Deleting it worked.

I have been going through similar issue, and deleting luarc.json helped. What am I missing here?

**Comment by max397574** [comment]
luarc.json overwrites config for luals
