### ISSUE TITLE
How can I uses lazydev without lspconfig?

### ISSUE THREAD

**Issue by Charlie-83** [folke/lazydev.nvim#27]
Docs just say

> If you don't use [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig), then you can use require('lazydev').find_workspace(buf?) to check if the buffer is part of an existing workspace or its libraries.

But I don't know what this is actually instructing me to do.

I use this autocommand to start `lua-ls`
```lua
autocmd("FileType", {
    pattern = "lua",
    callback = function()
        local root_dir = vim.fs.dirname(vim.fs.find({ "lazy-lock.json" })[1])
        local client = vim.lsp.start({
            name = "lua-ls",
            cmd = { "lua-language-server" },
            root_dir = root_dir,
        })
        vim.lsp.buf_attach_client(0, client)
    end,
})
```

I am using Lazy as my plugin manager and have
```lua
    {
        "folke/lazydev.nvim",
        ft = "lua",
        config = true,
    },
```

**Comment by folke** [comment]
That's only needed if you want to define custom workspaces.
Based on your code, you probably don't.

Aslo, please post in discussions next time!

**Comment by Charlie-83** [comment]
Sorry, have moved to discussions. It asked if I wanted the bug or feature template: I didn't want either so selected blank and didn't see that
