### ISSUE TITLE
bug: lazydev interferes with non-lua LSPs (ltex)

### ISSUE THREAD

**Issue by chrisgrieser** [folke/lazydev.nvim#29]
### Did you check docs and existing issues?

- [X] I have read all the lazydev.nvim docs
- [X] I have searched the existing issues of lazydev.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

macOS 14.4.1 (arm)

### Describe the bug

So this is a really weird one, which actually took me a few hours to reproduce / figure out. 💀 

lazydev apparently interferes with other LSPs that are *not* `lua-ls`. I noticed this issue with `ltex`, but not with other LSPs (though I do not use many LSPs, so it might also affect other LSPs).

Concretely, when `ltex` starts after lazydev is active, the settings passed to `ltex` via lsp-config are ignored. This does not happen when using neodev.

### Steps To Reproduce

1. Run the minimal config below (with lazydev). 
2. Open any lua file, to ensure lazydev is active.
3. Open this markdown file:

```md
# Spellings

This one should not get a warning, as it is part of the dictionary:
- mistkae

This one should get a warning:
- speling
```

4. Wait a bit (ltex is annoyingly slow to start up, takes ~30s for me.)
5. ltex should warn about "speling", but not about "mistkae", as the latter is added to the ltex dictionary. However, ltex reports both.
6. Remove lazydev from the config, and then repeat the steps above. Now ltex correctly only warns about "speling", but not "mistkae".

---

Note: on Linux devices, mason does not include a Java RE, which ltex requires to work.

### Expected Behavior

lazydev should not interfere with the config of other LSPs

### Repro

```Lua
local plugins = {
	{ "folke/lazydev.nvim", ft = "lua", opts = true },
	{
		"neovim/nvim-lspconfig",
		-- dependencies = "folke/neodev.nvim",
		config = function()
			require("lspconfig").lua_ls.setup {}
			require("lspconfig").ltex.setup {
				settings = {
					ltex = {
						dictionary = {
							["en-US"] = { "mistkae" },
						},
					},
				},
			}
		end,
	},
	{
		"WhoIsSethDaniel/mason-tool-installer.nvim",
		dependencies = { "williamboman/mason.nvim", opts = true },
		opts = {
			ensure_installed = { "lua-language-server", "ltex-ls" },
			run_on_start = true,
		},
	},
}

--------------------------------------------------------------------------------
for _, name in ipairs { "config", "data", "state", "cache" } do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = "/tmp/nvim-debug/" .. name
end
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if vim.uv.fs_stat(lazypath) == nil then
	local lazyrepo = "https://github.com/folke/lazy.nvim"
	vim.system({ "git", "clone", "--filter=blob:none", lazyrepo, "--branch=stable", lazypath }):wait()
end
vim.opt.runtimepath:prepend(lazypath)
require("lazy").setup(plugins)
```

**Comment by folke** [comment]
Damn, looks like lspconfig passes the same objects around for different LSP servers!
https://github.com/neovim/nvim-lspconfig/blob/92166b89ab4b3d60f24e58170cac53b7141fd032/lua/lspconfig/util.lua#L17

I can fix it already in lazydev, but this should aso be fixed upstream.

**Comment by folke** [comment]
Fixed and thank you for letting me know!

**Comment by chrisgrieser** [comment]
Thanks for the quick fix as always!
