### ISSUE TITLE
feature: Add support for coc.nvim

### ISSUE THREAD

**Issue by sajjathossain** [folke/lazydev.nvim#38]
### Did you check the docs?

- [X] I have read all the lazydev.nvim docs

### Is your feature request related to a problem? Please describe.

no.

### Describe the solution you'd like

I use coc.nvim. I want to get the intellesence support while I'm working on my neovim config

### Describe alternatives you've considered

I tried to use cmp. that works but I use coc.nvim

**Comment by max397574** [comment]
You can easily use the plugin without the completion source and you'll get completions for most things
https://github.com/folke/lazydev.nvim/discussions/52
