### ISSUE TITLE
feature: load library on filename

### ISSUE THREAD

**Issue by al1-ce** [folke/lazydev.nvim#39]
### Did you check the docs?

- [X] I have read all the lazydev.nvim docs

### Is your feature request related to a problem? Please describe.

I'm adding xmake library definitions which all live in global space (i.e without `require("xmake")`), so all of functions like `add_rules`, `target`.. that are defined by xmake are suggested in all lua files

### Describe the solution you'd like

Allow loading library when opening file with certain name, i.e with this configuration:
```lua
{
    'folke/lazydev.nvim',
    ft = "lua",
    opts = {
        library = {
            { "xmake-luals-addon/library", file = { "xmake.lua" } },
        }
    },
    dependencies = {
        "LelouchHe/xmake-luals-addon"
    }
}
```
xmake-luals-addon would only load when I'm opening `xmake.lua`

### Describe alternatives you've considered

Writing enable function that would detect filename, but that'd colide with other library definitions

**Comment by folke** [comment]
Isn't something like the below enough?

```lua
{ "LuaCATS/luassert", name = "luassert-types", lazy = true },
  { "LuaCATS/busted", name = "busted-types", lazy = true },
  {
    "folke/lazydev.nvim",
    opts = function(_, opts)
      vim.list_extend(opts.library, {
        { path = "luassert-types/library", words = { "assert" } },
        { path = "busted-types/library", words = { "describe" } },
      })
    end,
  },
```

**Comment by al1-ce** [comment]
No it's not enough

Problem is that all of the xmake functions are in global scope and have no common denominator

Here's example xmake:
```lua
-- xmake.lua
target("library")
    set_kind("static")
    add_files("src/library/*.c")

target("test")
    set_kind("binary")
    add_files("src/*.c")
    add_deps("library")
```

And same thing would be apply for premake:
```lua
-- premake5.lua
workspace "HelloWorld"
   configurations { "Debug", "Release" }

project "HelloWorld"
   kind "ConsoleApp"
   language "C"
   targetdir "bin/%{cfg.buildcfg}"

   files { "**.h", "**.c" }

   filter "configurations:Debug"
      defines { "DEBUG" }
      symbols "On"

   filter "configurations:Release"
      defines { "NDEBUG" }
      optimize "On"
```

Both of them use global space functions and don't have unique enough words that you wouldn't encounter when coding normally to identify by, so identifying by file is needed

**Comment by folke** [comment]
I don't see the issue tbh. Just add all the words? Or at least the most common ones?

**Comment by folke** [comment]
You could probably also just add `---@module 'xmake'` to the top of the file

**Comment by folke** [comment]
or feel free to provide a PR...

**Comment by al1-ce** [comment]
I'll do a PR then, could you reopen issue please?
