### ISSUE TITLE
feature: support `---@module` annotation

### ISSUE THREAD

**Issue by datwaft** [folke/lazydev.nvim#4]
### Did you check the docs?

- [X] I have read all the lazydev.nvim docs

### Is your feature request related to a problem? Please describe.

It would be useful to be able to use the [`---@module` annotation](https://luals.github.io/wiki/annotations/#module) instead of `require()` to load the types of a specific module.

e.g.

```lua
return {
  "stevearc/conform.nvim",
  ---@type conform.setupOpts
  opts = {
    -- ...
  },
}
```

In this case unless I used the `library` to always load conform types it would give me an error.

Right now I can `require("conform")` but it would be useful to also be able to use the [`---@module` annotation](https://luals.github.io/wiki/annotations/#module) for that when I only need the types.

### Describe the solution you'd like

```lua
return {
  "stevearc/conform.nvim",
  ---@module "conform"
  ---@type conform.setupOpts
  opts = {
    -- ...
  },
}
```

This should be the same as doing requiring `conform` somewhere in the file.

```lua
require("conform") -- This is going to fail because `conform` is not loaded yet.

return {
  "stevearc/conform.nvim",
  ---@type conform.setupOpts
  opts = {
    -- ...
  },
}
```

### Describe alternatives you've considered

Right now we can require the library somewhere in the file or use the `library` option.

```lua
{
  "folke/lazydev.nvim",
  ft = "lua",
  opts = {
    library = {
      vim.env.LAZY .. "/conform.nvim",
    },
  },
}
```

### Additional context

See https://luals.github.io/wiki/annotations/#module for the documentation for that annotation.

**Comment by TymekDev** [comment]
That's awesome! Thank you for showing how to get suggestions in `opts` for lazy.nvim.

@folke I think describing this would be an awesome addition to lazy.nvim configuration guide!
