### ISSUE TITLE
feature: lazy.nvim spec integration

### ISSUE THREAD

**Issue by WilliamHsieh** [folke/lazydev.nvim#58]
### Did you check the docs?

- [X] I have read all the lazydev.nvim docs

### Is your feature request related to a problem? Please describe.

currently it's possible to get type annotation through the traditional `require("plugin").setup { opts }` function call, however, when using lazy.nvim, most of the config are defined in `plugins.opts`, in this case, type annotation in opts are not provided.,

### Describe the solution you'd like

support type annotation in `lazy.nvim` spec, particularly in the `plugins.opts` field.

### Describe alternatives you've considered

use the traditional `setup` call in `plugins.config`

**Comment by folke** [comment]
Just add `---@module 'cmp'` for example and then add a correct type annotation to the opts field.

**Comment by WilliamHsieh** [comment]
Cool! didn't realize it was intended to be used like this. Thank you very much.
