### ISSUE TITLE
bug: nvim-cmp for lazydev showing "Unknown Source Name"

### ISSUE THREAD

**Issue by GitMurf** [folke/lazydev.nvim#62]
### Did you check docs and existing issues?

- [X] I have read all the lazydev.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of lazydev.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-522+g619d005ac

### Operating system/version

Windows 11

### Describe the bug

I cannot for the life of me figure out how to get the nvim-cmp integration working with lazydev. I keep getting the "unknown source" when looking at CmpStatus.

I have tried every which way to configure it with no luck. I have tried adding it to default cmp sources config as well as doing a setup.filetype for lua to just add the lazydev source for lua files. Nothing has worked.

![image](https://github.com/user-attachments/assets/9802f04a-2b4b-4002-94c8-aa624468de09)

Thanks in advance for the help!

### Steps To Reproduce

Setup lazydev with default config and add lazydev as a cmp source.

### Expected Behavior

lazydev cmp source should work and show as such in the cmpstatus.

**Comment by MarcoBuess** [comment]
I'm experiencing the same issue, but `nvim-cmp` will provide suggestions anyway. It just doensn't show signature help in the cmp menu, which I'm not sure if it is a `lazydev` or `nvim-cmp` issue. Maybe someone can clear things up?

**Comment by GitMurf** [comment]
> I'm experiencing the same issue, but `nvim-cmp` will provide suggestions anyway. It just doensn't show signature help in the cmp menu, which I'm not sure if it is a `lazydev` or `nvim-cmp` issue. Maybe someone can clear things up?

You should already be getting suggestions without adding lazydev for cmp as far as I know. The lazydev for cmp is supposed to be for showing all the plugins in require() calls which mine does not work. Are you getting all your plugins showing up in require() calls?

**Comment by MarcoBuess** [comment]
You're right. What I'm experiencing is from the `cmp-nvim-lua` source, I just got confused. But as you're saying `require()` doesn't bring up any modules for me either.

**Comment by tigion** [comment]
I only see it when I load lazydev.nvim also as a dependency for nvim-cmp. But I think this breaks the lazy loading of lazydev.nvim.

`:CmpStatus`
```md
# ready source names
- luasnip
- path
- buffer
- lazydev
- nvim_lsp:lua_ls
```
And a `require('t` in a lua file brings module suggestions.

<details>
  <summary>My *lsp.lua* with lazydev.nvim config</summary>

```lua
return {
  {
    'neovim/nvim-lspconfig',
    ...
  },
  ...
  {
    'folke/lazydev.nvim', -- Configures LuaLS for editing your Neovim config
    dependencies = {
      { 'Bilal2453/luvit-meta', lazy = true }, -- optional `vim.uv` typings
    },
    ft = 'lua', -- only load on lua files
    opts = {
      library = {
        -- See the configuration section for more details
        -- Load luvit types when the `vim.uv` word is found
        { path = 'luvit-meta/library', words = { 'vim%.uv' } },
      },
    },
  },
  { -- optional completion source for require statements and module annotations
    'hrsh7th/nvim-cmp',
    opts = function(_, opts)
      opts.sources = opts.sources or {}
      table.insert(opts.sources, {
        name = 'lazydev',
        group_index = 0, -- set group index to 0 to skip loading LuaLS completions
      })
    end,
  },
}
```

</details>

<details>
  <summary>My *cmp.lua* with nvim-cmp config</summary>

```lua
return {
  'hrsh7th/nvim-cmp',
  dependencies = {
    ...
    'folke/lazydev.nvim', -- TODO: Is here needed to get source `lazydev` from lsp.lua to work
  },
  opts = function()
    local cmp = require('cmp')
    ...

    return {
      ...
      sources = cmp.config.sources({
        { name = 'nvim_lsp' },
        { name = 'luasnip' },
        { name = 'buffer', keyword_length = 3, max_item_count = 10 },
        { name = 'path' },
      }),
      ...
    }
    end,
}
```

</details>

**Comment by GitMurf** [comment]
@folke i see you marked this as not planned. Are you able to guide us on what we are doing wrong to get Cmp source to work? Thanks!!
