### ISSUE TITLE
bug: fs_stat not recognized if using `vim.uv or vim.loop`

### ISSUE THREAD

**Issue by lorypelli** [folke/lazydev.nvim#65]
### Did you check docs and existing issues?

- [X] I have read all the lazydev.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of lazydev.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1725453128

### Operating system/version

Arch Linux Kernel 6.10 Endeavour OS

### Describe the bug

![image](https://github.com/user-attachments/assets/567fb587-ba15-4988-8a1f-be3c788c0b35)

### Steps To Reproduce

vim.uv was added in 0.10 (rename of vim.loop), so we should use both to not break anything

### Expected Behavior

fs_stat is defined in both, before it was used with vim.loop, but they are the same

**Comment by folke** [comment]
Sorry, but this does work. If it doesn't your Neovim version must be messed up. Closing

**Comment by 3rd** [comment]
Same issue, and LSP goes here https://github.com/neovim/neovim/blob/079e5f4f9b67a5aa2c1b481ce78711bf8c76caea/runtime/lua/vim/_meta.lua#L6 which would explain the lack of completions.

**Comment by gennaro-tedesco** [comment]
I see the same diagnostic for `fs_stat` as undefined field, moreover for others of the family `vim.uv` (in particular `vim.uv.fs_realpath`). I do have the settings to be
```lua
opts = {
      library = {
        { path = "${3rd}/luv/library", words = { "vim%.uv" } },
      },
    },
```
perhaps one shall indicate additional libraries too (or does it work on nightly only? I am currently using `v0.10.4`)?
