### ISSUE TITLE
feature: Update the readme to explain how to use lazydev without lazy.nvim plugin manager

### ISSUE THREAD

**Issue by mairs8** [folke/lazydev.nvim#67]
### Did you check the docs?

- [X] I have read all the lazydev.nvim docs

### Is your feature request related to a problem? Please describe.

i was trying to setup lazydev and noticed that i couldn't get it to show me nvim api completions. following some debugging and reading i saw that in the readme plugin requirements it states:

- lazy.nvim plugin manager
- OR a plugin manager that uses Neovim's native package system

I am nixos user and install all my plugins via my nixos config files. I do not use the lazy.nvim plugin manager. How do i use this plugin outside of the lazy.nvim plackage manager system. It would be helpful if the readme could explain the more native way to get this set up. 

### Describe the solution you'd like

1) add instructions to the readme to explain how to install with nixos and/or setups not using lazy.nvim package manager.
2) changes to the codebase so that lazydev features are available without requiring lazy.nvim package manager.

### Describe alternatives you've considered

na

**Comment by folke** [comment]
Just set it up like any oher plugin.
