### ISSUE TITLE
bug: blink instalation documentation

### ISSUE THREAD

**Issue by rodhash** [folke/lazydev.nvim#77]
### Did you check docs and existing issues?

- [X] I have read all the lazydev.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of lazydev.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-1028+g6dad1f9f1

### Operating system/version

MacOS 15.1.1

### Describe the bug

It seems we have a bug in the README about blink's installation.

Installing blink as suggested [here](https://github.com/folke/lazydev.nvim?tab=readme-ov-file#-installation) got me some errors.

Then checking blink's repo I found out [we need](https://github.com/Saghen/blink.cmp/issues/44#issuecomment-2400909434) to specify a version.

Following what's suggested in blink's repo, this solved the error for me:
```lua
    { -- optional blink completion source for require statements and module annotations
      "saghen/blink.cmp",
      version = 'v0.*',
...
```

### Steps To Reproduce

1. Trying installing blink without providing a version returns this error:
```lua
   Error  Error executing vim.schedule lua callback: .../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:9: Error while downloading blink.cmp pre-built binary: Can't download from github due to not being on a git tag and no fuzzy.prebuilt_binaries.force_version set, but found no built version of the library. Either run `cargo build --release` via your package manager, switch to a git tag, or set `fuzzy.prebuilt_binaries.force_version` in config. See the README for more info.
```

### Expected Behavior

No error while installing lazydev's dep.

### Repro

```lua
I dont have a minimal created for this.
```

**Comment by folke** [comment]
How is that a lazydev issue??

**Comment by rodhash** [comment]
It's not an issue per se but just a documentation update. Shouldn't we update the readme to add the version?

**Comment by folke** [comment]
You of course always install a plugin by reading it's docs.
That snippet of lazydev works perfectly fine if you also followed the blink installation docs.
With lazy, property merging that's not an issue
